# Travis CI configuration file
sudo: false

language: c

script: 
   - ./autogen.sh && ./configure && make 
   - package_cloud push resnostyle/snapraid/ubuntu/debs /home/travis/build/resnostyle/snapraid

compiler:
  - clang
  - gcc

os:
  - linux

before_install:
  - gem install package_cloud
