# Travis CI configuration file
sudo: false

language: c

script: autoreconf -i && ./configure && make distcheck

compiler:
  - clang
  - gcc

os:
  - linux

before_install:
  - gem install package_cloud

script:
    - package_cloud push resnostyle/snapraid/ubuntu snapraid
