# Travis CI configuration file
dependencies:
  pre:
    - gem install package_cloud
    
sudo: false

language: c

script: autoreconf -i && ./configure && make distcheck

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

deployment:
  production:
    branch: master
    commands:
      - package_cloud push resnostyle/snapraid snapraid
