# Travis CI configuration file
sudo: false

language: c

script: 
   - autoreconf -i && ./configure && make &&  make check & make install
   - package_cloud push resnostyle/snapraid/ubuntu/debs snapraid

compiler:
  - clang
  - gcc

os:
  - linux

before_install:
  - gem install package_cloud
